name: ramp_ci_2017
channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.22.0=py36_0
- bkcharts=0.2=py36_0
- blas=1.1=openblas
- bleach=2.0.0=py36_0
- bokeh=0.12.6=py36_0
- bottleneck=1.2.1=np113py36_0
- ca-certificates=2017.7.27.1=0
- cartopy=0.15.1=np113py36_3
- certifi=2017.7.27.1=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.4=py36_0
- click=6.7=py36_0
- cloudpickle=0.4.0=py36_0
- coverage=4.4.1=py36_0
- cryptography=2.0.3=py36_0
- curl=7.54.1=0
- cycler=0.10.0=py36_0
- dask=0.15.2=py36_0
- dask-core=0.15.2=py36_0
- decorator=4.1.2=py36_0
- distributed=1.18.3=py36_0
- entrypoints=0.2.3=py36_1
- freetype=2.7=1
- geos=3.5.1=1
- gitdb2=2.0.2=py36_0
- gitpython=2.1.5=py36_0
- h5netcdf=0.4.0=py36_0
- h5py=2.7.1=np113py36_0
- hdf4=4.2.12=0
- hdf5=1.8.18=0
- heapdict=1.0.0=py36_0
- html5lib=0.999999999=py36_0
- icu=58.1=1
- idna=2.5=py36_0
- imageio=2.2.0=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.0=py36_1
- jedi=0.10.2=py36_0
- jinja2=2.9.6=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- krb5=1.14.2=0
- libffi=3.2.1=3
- libgfortran=3.0.0=0
- libiconv=1.14=4
- libnetcdf=4.4.1.1=5
- libpng=1.6.28=0
- libsodium=1.0.10=0
- libssh2=1.8.0=1
- libtiff=4.0.6=7
- libxml2=2.9.4=4
- libxslt=1.1.29=5
- locket=0.2.0=py36_1
- lxml=3.8.0=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=py36_2
- mistune=0.7.4=py36_0
- msgpack-python=0.4.8=py36_0
- nbconvert=5.2.1=py36_1
- nbformat=4.3.0=py36_0
- ncurses=5.9=10
- netcdf4=1.2.9=py36_1
- networkx=1.11=py36_0
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_blas_openblas_200
- olefile=0.44=py36_0
- openblas=0.2.19=2
- openssl=1.0.2l=0
- owslib=0.14.0=py36_1
- pandas=0.20.3=py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- partd=0.3.8=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_0
- proj4=4.9.3=4
- prompt_toolkit=1.0.15=py36_0
- psutil=5.2.2=py36_0
- ptyprocess=0.5.2=py36_0
- py=1.4.34=py36_0
- pycparser=2.18=py36_0
- pyepsg=0.3.2=py36_0
- pygments=2.2.0=py36_0
- pyopenssl=17.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyproj=1.9.5.1=py36_0
- pyqt=5.6.0=py36_4
- pyshp=1.2.11=py36_0
- pysocks=1.6.7=py36_0
- pytest=3.2.1=py36_0
- pytest-cov=2.5.1=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np113py36_0
- pyyaml=3.12=py36_1
- pyzmq=16.0.2=py36_2
- qt=5.6.2=h9e3eb04_4
- qtconsole=4.3.1=py36_0
- readline=6.2=0
- requests=2.18.4=py36_1
- scikit-image=0.13.0=py36_1
- scikit-learn=0.19.0=py36_blas_openblas_201
- scipy=0.19.1=py36_blas_openblas_202
- setuptools=36.3.0=py36_0
- shapely=1.6.1=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- smmap2=2.0.3=py36_0
- sortedcontainers=1.5.7=py36_0
- sqlite=3.13.0=1
- tblib=1.3.2=py36_0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.19=2
- toolz=0.8.2=py36_0
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.22=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.0.2=py36_0
- xarray=0.9.6=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zeromq=4.2.1=1
- zict=0.1.2=py36_0
- zlib=1.2.11=0
- pip:
  - ipython-genutils==0.2.0
  - joblib==0.11
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - jupyterlab-launcher==0.4.2
  - markdown==2.6.9
  - prompt-toolkit==1.0.15
prefix: /Users/dgagne/anaconda3/envs/ramp

